[build]
builder = "nixpacks"

[build.nixpacks]
providers = ["node"]

[build.nixpacks.variables]
NODE_VERSION = "18"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
