[build]
builder = "dockerfile"

[build.dockerfile]
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
startCommand = "serve -s dist -l $PORT --no-clipboard"
